#!/bin/bash

sudo rm -rf /etc/xray
sudo rm -rf /etc/v2ray
sudo rm -rf /etc/nsdomain
sudo rm -rf /etc/per

# Membuat direktori yang diperlukan
sudo mkdir -p /etc/xray
sudo mkdir -p /etc/v2ray
sudo mkdir -p /etc/nsdomain

MYIP=$(wget -qO- icanhazip.com);
apt install jq curl -y
#read -p "Masukan Domain (contoh : Dragon)" domen
DOMAIN=tepllovpn.eu.org
sub="bt-$(</dev/urandom tr -dc a-z0-9 | head -c5)"
dnss=${sub}.tepllovpn.eu.org
CF_ID=bangtepllo752@gmail.com
CF_KEY=aefeaef07622fac408d5a975087a42b698a57
set -euo pipefail
IP=$(wget -qO- icanhazip.com);
echo "Updating DNS for ${dnss}..."
ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${dnss}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#RECORD}" -le 10 ]]; then
     RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${dnss}'","content":"'${IP}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi

RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${dnss}'","content":"'${IP}'","ttl":120,"proxied":false}')

sudo touch /etc/xray/domain
sudo touch /etc/v2ray/domain
sudo touch /etc/xray/slwdomain
sudo touch /etc/v2ray/scdomain

# Menulis domain ke file yang sesuai
sudo echo "$dnss" > /root/domain
sudo echo "$dnss" > /root/scdomain
sudo echo "$dnss" > /etc/xray/scdomain
sudo echo "$dnss" > /etc/v2ray/scdomain
sudo echo "$dnss" > /etc/xray/domain
sudo echo "$dnss" > /etc/v2ray/domain

echo "IP=$dnss" > /var/lib/ipvps.conf
